# Generated by Django 4.2.1 on 2023-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
