# Generated by Django 4.2.1 on 2023-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pontoturistico_aprovado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Pontos Turísticos'},
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
