# Generated by Django 4.2.1 on 2023-05-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ('data',), 'verbose_name_plural': 'Comentários'},
        ),
    ]
