# Generated by Django 4.2.1 on 2023-05-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_alter_avaliacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
