# Generated by Django 4.2.1 on 2023-05-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('atracoes', '0002_alter_atracao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
    ]
